### ISSUE TITLE
index.md links

### ISSUE THREAD

**Issue by hiroyuki-sato** [zig-by-example/zig-by-example.github.io#15]
Hello, members.

Thank you for creating this example page.

[Links of this page](https://zigbyexample.github.io) is broken.

Shall I create a PR?

* [Command-Line Arguments](https://zigbyexample.github.io/command_line_arguments)
* [Reading input](https://zigbyexample.github.io/read_input)
* [Read/Write File](https://zigbyexample.github.io/read_write_file)
* [Directory Listing](https://zigbyexample.github.io/directory_listing)
* [Spawning Subprocess](https://zigbyexample.github.io/spawn_subprocess)
* [Hashing](https://zigbyexample.github.io/hashing)
* [TCP Connection](https://zigbyexample.github.io/tcp_connection)
* [Mutex](https://zigbyexample.github.io/mutex)
* [Atomics](https://zigbyexample.github.io/atomics)

```
* [Atomics](https://zigbyexample.github.io/atomics)
* [Command-Line Arguments](https://zigbyexample.github.io/command_line_arguments)
* [Directory Listing](https://zigbyexample.github.io/directory_listing)
* [Hashing](https://zigbyexample.github.io/hashing)
* [Mutex](https://zigbyexample.github.io/mutex)
* [Reading input](https://zigbyexample.github.io/read_input)
* [Read/Write File](https://zigbyexample.github.io/read_write_file)
* [Spawning Subprocess](https://zigbyexample.github.io/spawn_subprocess)
* [TCP Connection](https://zigbyexample.github.io/tcp_connection)
```

I'm a newbie to Zig language. So I used a script like the one below

```
awk '/^title:/{ printf "* [%s]",$0 }/permalink/{ printf "(https://zigbyexample.github.io%s)\n",$2 }' template/*.md | sed -e 's/title: //'
```

**Comment by alichraghi** [comment]
just make the PR

**Comment by hiroyuki-sato** [comment]
Hello, @alichraghi 
Thank you for your comment. I created #16.
