### ISSUE TITLE
Plans for further examples

### ISSUE THREAD

**Issue by craig-mcd** [zig-by-example/zig-by-example.github.io#6]
Are there plans or ideas for more examples? Are you willing to take contributions from the community? If so, what are the areas you are looking for.

I didn't want to submit anything if there was already plans.

**Comment by alichraghi** [comment]
there are currently 4 projects with the same goal as zig by example, one of which is just a domain. i'll try my best to keep this project active, but I'm busy right now and i do not have a specific idea in mind. any contribution is welcome and i'm glad to share it if you have an idea :)
https://zig-by-example.github.io/
https://zigbyexample.com/ 
https://zig-by-example.com/
https://nofmal.github.io/zig-with-example/

**Comment by craig-mcd** [comment]
Great, thanks for that.
