### ISSUE TITLE
subprocess/child_process: expect correct exit status

### ISSUE THREAD

**Issue by matu3ba** [zig-by-example/zig-by-example.github.io#7]
You nicely check for the correct tag, but you miss to check the status of the tag with `try testing.expectEqual(@as(u8, 0), ret_val.Exited);`.
For these functions there will be hopefully soon a helper function in `std.testing`:
```zig
        try testing.expectEqualSlices(u8, exited, std.meta.tagName(ret_val));
        try testing.expectEqual(@as(u8, 0), ret_val.Exited);
```

**Comment by matu3ba** [comment]
my bad actually, this can be simplified to
```zig
try testing.expectEqual(ret_val, .{ .Exited = 0 });
```
because the enum tag is explicit. This would even be the case for a `union` in `Debug` builds.

**Comment by alichraghi** [comment]
https://github.com/zig-by-example/zig-by-example.github.io/commit/77116b032683f0b64a2193e918a2c5e51fd5eadb
