### ISSUE TITLE
tcp server is missing a client

### ISSUE THREAD

**Issue by matu3ba** [zig-by-example/zig-by-example.github.io#8]
It would be probably very nice to spawn both from a separate process as independent processes to be killed after some time or so

That way you could also explain spawning "independent processes" and not only "child_processes".

**Comment by alichraghi** [comment]
good point. i'll take [this](https://github.com/ziglang/zig/blob/5fbae9cd6fe7a53d85ad6dd20cab75f7b835f0ad/lib/std/net/test.zig#L142-L183) std/net test as an example

**Comment by alichraghi** [comment]
https://github.com/zig-by-example/zig-by-example.github.io/commit/77116b032683f0b64a2193e918a2c5e51fd5eadb
